# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0006_openinghours_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('featured_image', models.ImageField(blank=True, default='', help_text='Recommended 900x500', max_length=1024, upload_to='slide')),
                ('featured_order', models.IntegerField(default=0)),
                ('publish_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('unpublish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SlideBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
