# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160918_1001'),
        ('flatpages', '0001_initial'),
        ('site', '0008_slidebanner_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Entry'),
        ),
        migrations.AddField(
            model_name='slide',
            name='flatpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage'),
        ),
    ]
