# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0010_slide_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
