# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0011_auto_20180926_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slidebanner',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
