# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0012_auto_20180926_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['-is_active', 'featured_order']},
        ),
        migrations.AddField(
            model_name='slide',
            name='what_to_show',
            field=models.CharField(choices=[('url', 'url'), ('content', 'content'), ('flatpage', 'flatpage'), ('entry', 'entry')], default='content', max_length=32),
            preserve_default=False,
        ),
    ]
