# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0013_auto_20180926_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='entry',
        ),
    ]
