# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0014_remove_slide_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['-is_active', 'slider', 'featured_order', 'publish_at']},
        ),
        migrations.AlterField(
            model_name='slide',
            name='slider',
            field=models.CharField(choices=[('home', 'home'), ('games', 'games'), ('special', 'specials')], max_length=32),
        ),
        migrations.AlterField(
            model_name='slide',
            name='what_to_show',
            field=models.CharField(blank=True, choices=[('', ''), ('url', 'url'), ('content', 'content'), ('flatpage', 'flatpage'), ('entry', 'entry')], default='', max_length=32),
        ),
    ]
