# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 07:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180430_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('numbers_confirmed', 'Numbers Confirmed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='booked', max_length=50),
        ),
    ]
