# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 01:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20181127_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(105), django.core.validators.MinValueValidator(1)], verbose_name='Number of people'),
        ),
    ]
