# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20181127_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid_deposit',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('deposit_required', 'Deposit Required'), ('deposit_paid', 'Deposit Paid'), ('numbers_confirmed', 'Numbers Confirmed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='booked', max_length=50),
        ),
    ]
