# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('issued_to', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('added_by', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('redeemed_by', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_expires', models.DateTimeField()),
                ('date_redeemed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
