# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20181107_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='notes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
