# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20181108_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftvoucher',
            old_name='date_expires',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='giftvoucher',
            old_name='date_issued',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='giftvoucher',
            old_name='date_redeemed',
            new_name='redemmed_date',
        ),
    ]
