# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_auto_20181108_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='issued_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='redemmed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
