# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_auto_20181108_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='is_legacy',
            field=models.BooleanField(default=True),
        ),
    ]
