# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_auto_20181108_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftvoucher',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='added_by',
            field=models.CharField(default='admin', max_length=64),
            preserve_default=False,
        ),
    ]
