# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_auto_20181108_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='is_issued',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
