# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_item_itemtype_menuimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menutype',
            options={'ordering': ['order', 'pk'], 'verbose_name_plural': 'menus'},
        ),
        migrations.AddField(
            model_name='menuimage',
            name='width',
            field=models.CharField(default='100%', max_length=32),
        ),
        migrations.AddField(
            model_name='menutype',
            name='type',
            field=models.CharField(blank=True, choices=[('food', 'food'), ('drinks', 'drinks'), ('banquet', 'banquet'), ('games', 'games')], default='', max_length=32),
        ),
    ]
