# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20180921_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menuimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
